SillCo/Controllers/EquipmentController.cs
using SillCo.Data.List;
using SillCo.Models.Equipment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SillCo.Controllers
{
    public class EquipmentController : Controller
    {
        // GET: Equipment
        public ActionResult Index()
        {
            EquipmentList equipmentList = new EquipmentList();
            Dictionary<string, List<Equipment>> equipmentLists = new Dictionary<string, List<Equipment>>();
            equipmentLists.Add("Tools", equipmentList.Tools);
            equipmentLists.Add("Apparel", equipmentList.Apparel);
            equipmentLists.Add("Armor", equipmentList.Armor);
            equipmentLists.Add("Medical", equipmentList.Medical);
            equipmentLists.Add("Electrical", equipmentList.Electrical);
            equipmentLists.Add("Survival", equipmentList.Survival);
            equipmentLists.Add("Misc", equipmentList.Misc);

            return View(equipmentLists);
        }

        // GET: Equipment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Equipment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Equipment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Equipment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Equipment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Equipment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Equipment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SillCo/Controllers/ToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SillCo.Controllers
{
    public class ToolController : Controller
    {
        // GET: Tool
        public ActionResult Index()
        {
            ViewBag.Message = "Your tools page.";

            return View();
        }

        // GET: Tool/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Tool/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tool/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tool/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Tool/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tool/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Tool/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SillCo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SillCo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @Html.ActionLink("SillCo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-item nav-link active" })
                @Html.ActionLink("Pathfinder", "Index", "Pathfinder", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Character", "Index", "Character", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Jobs", "Jobs", "Home", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Tools", "Index", "Tool", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Weapons", "Index", "Equipment", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Armor", "Index", "Equipment", new { area = "" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Other", "Index", "Equipment", new { area = "" }, new { @class = "nav-item nav-link" })
            </div>
        </div>
        @Html.Partial("_LoginPartial")
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>